### ISSUE TITLE
Mysql driver

### ISSUE THREAD

**Issue by QuentinBisiaux** [tleon/docker-light-stack#2]
Bon  a chaque fois que je veux  lancer mes fixtures je me prends prends toujours le même problème sur tous les projets que j'ai essayé donc le problème doit clairement venir de chez moi.
In AbstractMySQLDriver.php line 93:                                                          
  An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused                                                           
In PDOConnection.php line 31                  
  SQLSTATE[HY000] [2002] Connection refused  
In PDOConnection.php line 27:                                 
  SQLSTATE[HY000] [2002] Connection refused 

Je ne sais pas où chercher pour régler ça. Tu aurais une idée?
See you

**Comment by tleon** [comment]
Le database url de ton .env symfo ? Il doit être de la forme user:pass@mysql:3306...

**Comment by QuentinBisiaux** [comment]
Effectivement je ne l'avais pas touché, après avoir jouer avec les ports a droite et gauche sans comprendre ce que je fesais ça marche. Merci beaucoup je peux enfin dev sans me poser la question de la machine sur laquelle je suis
